services:
  frontend:
    image: jassuwu/search-psgtech:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - SCRAPE_PSGTECH_SERVER=http://backend:8000
    networks:
      - psgoogle-network

  backend:
    image: jassuwu/scrape-psgtech:latest
    depends_on:
      - redis
    environment:
      - ADDR=:8000
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=HAHAVERYSTRONGPASSWORD
    networks:
      - psgoogle-network

  # ephemeral, no persistance, so no volumes
  redis:
    image: redis/redis-stack-server:latest
    environment:
      - REDIS_ARGS=--requirepass HAHAVERYSTRONGPASSWORD --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - psgoogle-network

networks:
  psgoogle-network:
    driver: bridge
